# Generated by Django 4.0.5 on 2022-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_qty', models.IntegerField(max_length=255)),
            ],
            options={
                'ordering': ['medicine_id'],
            },
        ),
    ]
